### ISSUE TITLE
Support for 4.3.0 previews

### ISSUE THREAD

**Issue by dasMulli** [joelverhagen/NuGetTools#12]
🙏 

@joelverhagen This tool is great and would be even greater with 4.3.0 (preview) support to reason about the `netstandard2.0` changes.

**Comment by Jonathan34** [comment]
pleeeeeease

**Comment by joelverhagen** [comment]
Done.
http://nugettoolsdev.azurewebsites.net/4.3.0-beta1-2418/framework-compatibility?project=net461&package=netstandard2.0

Thanks for the heads up.

**Comment by Jonathan34** [comment]
Thanks for adding this so quickly.

To ensure I interpret correctly: 
http://nugettoolsdev.azurewebsites.net/4.3.0-beta1-2418/framework-compatibility?project=net462&package=netstandard1.6

a netstandard 1.6 package should work properly in net462 project but you may get some missingmethods exception here and there.
Which means it is not a full support...? as per https://docs.microsoft.com/en-us/dotnet/articles/standard/library, 1.6 only supports 4.6.1 for tooling 2.0 but nothing for tooling 1.0.

**Comment by joelverhagen** [comment]
My knowledge about netstandard 2.0 is not up to date, sorry. I work in a different area of NuGet now so I haven't been up to date on the latest netstandard news.

All my tool does is call into NuGet APIs that determine compatibility between projects and packages. In other words, the correct interpretation of that page would be that NuGet thinks that a `net462` project can install `netstandard1.6` packages.
