### ISSUE TITLE
Parse Version gives incorrect SemVer result

### ISSUE THREAD

**Issue by ghost** [joelverhagen/NuGetTools#13]
![image](https://cloud.githubusercontent.com/assets/20977235/26804600/82eba444-4a16-11e7-9079-dd730cd08ae7.png)

Shouldn't SemVer also be 1.2.3?

**Comment by joelverhagen** [comment]
Ah! This is a confusing bit of wording on my part. I'll leave this issue open so I can improve this wording later.

What this line means is that the version string `1.2.3` adheres to [SemVer 1.0.0 specification](http://semver.org/spec/v1.0.0.html). NuGet also understands [SemVer 2.0.0](http://semver.org/spec/v2.0.0.html) version strings so this is meant to point out which SemVer specification NuGet thinks the version number is adhering to.

As an aside, note that there are some version strings that NuGet supports that are not adhering to the SemVer 1.0.0 _or_ 2.0.0 specification. For example, consider [`1.0.0.1`](https://nugettoolsdev.azurewebsites.net/4.3.0-beta1-2418/parse-version?version=1.0.0.1):
![image](https://user-images.githubusercontent.com/94054/28074694-1338daae-660e-11e7-8b3d-45ed74514fd3.png)

**Comment by joelverhagen** [comment]
I've clarified the message text. Let me know if you run into anything else!
