### ISSUE TITLE
Enable providing the dependencies section, for it has an effect in selecting the nearest framework

### ISSUE THREAD

**Issue by moh-hassan** [joelverhagen/NuGetTools#14]
In net461 projects, nuget may select the netstandard as the Nearest Framework, see the [example ](https://github.com/NuGet/Home/issues/7263)

An empty dependency group in the dependencies section will modify the Nearest Framework to be ,e.g, net45.

So, the dependencies section should be exist and evaluated in the same way as nuget tool. 

       <dependencies>
        <group targetFramework="net45"/>       
        <group targetFramework=".NETStandard1.5">
        <dependency id="System.Collections" version="4.0.11-rc2-24027" />
        <dependency id="System.Console" version="4.0.0-rc2-24027" />
          ........
     </group>

**Comment by joelverhagen** [comment]
Sorry about the... very long delay.

Could you help me understand where you would expect the dependencies section to be provided? Which tool? A new one? Or as an option to provide on the Framework > Get Nearest Framework tool?

You could test this case like this:
https://nugettoolsdev.azurewebsites.net/5.3.0/get-nearest-framework?project=net461&package=net45%0D%0A.NETStandard1.5

**Comment by joelverhagen** [comment]
Closing since I have not heard back. Feel free to file another issue if you're still interested.
